### PR TITLE
Added JavaScript Application Design book

### PR DESCRIPTION
**Pull request by bevacqua**

### CODE REVIEW

**Comment by ericelliott** [comment]
Thanks for the suggestion. I like your blog, but I haven't read this book. Is it available online?

**Comment by bevacqua** [comment]
Hey, not for free, but I can send you a free copy if you want

**Comment by ericelliott** [comment]
Sure. This list only includes my favorite resources, so I'll need to read it before I give my stamp of approval. Please follow [JS_Cheerleader](https://twitter.com/JS_Cheerleader) on Twitter and tweet at her saying you want to send me your book to arrange delivery. =)

**Comment by bevacqua** [comment]
I can just have Manning email you a copy. What's your email? You can DM me on twitter if you prefer

**Comment by ericelliott** [comment]
Can you send to @JS_Cheerleader? =)

**Comment by bevacqua** [comment]
I need an email address

On Tuesday, June 16, 2015, Eric Elliott <notifications@github.com> wrote:

> Can you send to @JS_Cheerleader? =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericelliott/essential-javascript-links/pull/12#issuecomment-112246372>
> .
>


-- 


github <https://github.com/bevacqua> · blog <http://blog.ponyfoo.com/> ·
twitter <https://twitter.com/nzgb> · book <http://bevacqua.io/buildfirst> ·
career <http://careers.stackoverflow.com/bevacqua> ·about
<http://bevacqua.io/>

**Comment by ericelliott** [comment]
Closing for now. Coordinate ebook delivery with [@JS_Cheerleader](https://twitter.com/js_cheerleader) on Twitter.

**Pull request closed without merging**
