### PR TITLE
Add Countly

### PR DESCRIPTION
**Pull request by gorkem-cetin**
Apart from this, how about separating Libraries to Libraries and Software & Products ?

### CODE REVIEW

**Comment by ericelliott** [comment]
Is there a homepage for the OSS project with a live demo?

**Comment by gorkem-cetin** [comment]
That would be the company page, http://count.ly or http://count.ly/newaccount

**Comment by ericelliott** [comment]
I'd love to test this out, but...

> Countly web analytics related plugins are currently available for Enterprise Edition, and will be available for Community Edition in January, 2016. Check back when we release Countly Community Edition v16.01.

In other words, dead in the water already...

**Comment by gorkem-cetin** [comment]
Currently when you download Github package, it's possible, if that is something interesting to you. 

If not, I'll ping you once again when the new release is there.

**Comment by ericelliott** [comment]
Is there a separate GitHub repo just for the JS SDK? Can I simply download the SDK from the repo without downloading the whole server app?

**Comment by gorkem-cetin** [comment]
It's on http://github.com/countly/countly-sdk-web

**Comment by ericelliott** [comment]
Cool. Would you like to re-open this when it has been officially released for community?

**Comment by gorkem-cetin** [comment]
Yes, will do. Many thanks.

**Comment by ericelliott** [comment]
:+1:

**Comment by gorkem-cetin** [comment]
So it's officially released :+1: 

https://medium.com/@countly/we-released-a-new-version-of-countly-and-we-are-so-proud-of-it-daa640b1a4dc

**Pull request merged**
